### ISSUE TITLE
This doesn't handle floating-point numbers properly.

### ISSUE THREAD

**Issue by ehberger** [tfeng/collection#1]

**Comment by ehberger** [comment]
Testcase: `new Set([1.1]).has(1.2)`

**Comment by tfeng** [comment]
Thanks for the message, ehberger! Yes this is a bug.

I will try to fix it as soon as I can, but if your use case is urgent, please feel free to fix it yourself and submit your patch.

**Comment by tfeng** [comment]
I think it has to do with the data type I use to store the values in C++.

**Comment by tfeng** [comment]
Resolved in 0.1.5.
